
!procedure $singleton()
    <size:8>//**[singleton]**//</size>
!endprocedure

!procedure $implementation()
    +<color:#CornflowerBlue>
!endprocedure

!procedure $optional($param)
//optional_parameter//
!endprocedure

!procedure $throws($class, $exception)
    $class ..> $exception : <<Throws>>
!endprocedure
 
!procedure $nested($outer_class, $inner_class)
    $outer_class +-- $inner_class
!endprocedure

!procedure $primary_key($field)
$field <color:#DarkOrange>//pk//</color>
!endprocedure

!procedure $foreign_key($field)
$field <color:#DarkOrchid>//fk//</color>
!endprocedure

!procedure $index($field)
$field <color:#DarkGoldenRod>//idx//</color>
!endprocedure

