@startuml GloomhavenUML
    !include includes/common/skinparams.iuml
    !include includes/gloomhaven_pckg_UML.iuml

    gloomhaven_model_pckg -[hidden]- Legend
    class Sth
    class TAKSOPDKAS
    class asokdpoaskpo
    Sth -- TAKSOPDKAS
    class Again
@enduml