name: Generate SVGs from PlantUML

on:
  push:
    branches: [ "test_for_actions" ]

jobs:
  generate-svgs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Generate SVGs
        run: |
          PLANTUML="path/to/plantuml.jar"
          UML_DIR="path/to/your/uml/files"
          SVG_DIR="path/to/your/svg/files"
          mkdir -p "$SVG_DIR"

          for UML_FILE in "$UML_DIR"/*.iuml "$UML_DIR"/*.puml; do
              BASENAME=$(basename "$UML_FILE")
              SVG_FILE="$SVG_DIR/${BASENAME%.*}.svg"
              java -jar "$PLANTUML" -tsvg -o "$SVG_DIR" "$UML_FILE"
          done

      - name: Commit SVGs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
          # Set up the Personal Access Token
          GH_PAT="${{ secrets.GH_PAT_PLANT_UML }}"
          git remote set-url origin "https://$GH_PAT@github.com/${{ github.repository }}.git"

          git add "$SVG_DIR"
          git commit -m "Generate SVGs from PlantUML"
          git push
