name: Generate PlantUML Diagrams

on:
  push:
    branches: [ "test_for_actions" ]

jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@master
      with:
        path: plantUML/out
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT_PLANT_UML }}